import 'dotenv/config';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PrismaService } from '../src/infrastructure/database/prisma/prisma.service';
import { AuditService } from '../src/modules/audit/application/services/audit.service';
import { InventoryService } from '../src/modules/inventory/inventory.service';
import { PurchasesService } from '../src/modules/purchases/application/services/purchases.service';
import { SupplyWorkflowService } from '../src/modules/purchases/application/services/supply-workflow.service';
import { RetaceosService } from '../src/modules/purchases/application/services/retaceos.service';
import { PurchaseReceiptsService } from '../src/modules/purchases/application/services/purchase-receipts.service';

const db = new PrismaService(), key = 'QA-EDGE-' + randomUUID().slice(0, 8);
const rollback = new Error('ROLLBACK_SUPPLY_EDGE_QA');
const day = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/El_Salvador' }).format(new Date());
const future = new Date(Date.now() + 7 * 86400000).toISOString();
async function reject(work: Promise<unknown>, status = 409) { await assert.rejects(work, (error: any) => error.getStatus?.() === status); }
async function main() {
  let verified = false;
  try {
    await db.$transaction(async tx => {
      const scoped = new Proxy(tx, { get(target, property) {
        if (property === '$transaction') return (work: any) => typeof work === 'function' ? work(tx) : Promise.all(work);
        const value = Reflect.get(target, property); return typeof value === 'function' ? value.bind(target) : value;
      } }) as unknown as PrismaService;
      const audit = new AuditService(scoped), inventory = new InventoryService(scoped, audit);
      const purchases = new PurchasesService(scoped, audit, inventory), supply = new SupplyWorkflowService(scoped, audit, inventory, purchases);
      const receipts = new PurchaseReceiptsService(scoped, audit, inventory), retaceos = new RetaceosService(scoped, audit);
      const config = await tx.erpConfiguration.findUniqueOrThrow({ where: { id: 1 }, include: { company: true, generalWarehouse: true } });
      const companyId = config.companyId, general = config.generalWarehouse!;
      const actor = await tx.user.findFirstOrThrow({ where: { isActive: true, deletedAt: null, userRoles: { some: { role: { name: 'superadmin' } } } } });
      const user: any = { sub: actor.id, roles: ['superadmin'], permissions: [] };
      const category = await tx.productCategory.create({ data: { name: key } });
      const subcategory = await tx.productSubcategory.create({ data: { categoryId: category.id, name: key } });
      const buyUnit = await tx.productUnit.create({ data: { name: key + ' compra', type: 'purchase' } });
      const saleUnit = await tx.productUnit.create({ data: { name: key + ' venta', type: 'sale' } });
      const products = [];
      for (let index = 0; index < 2; index++) products.push(await tx.product.create({ data: { companyId, categoryId: category.id, subcategoryId: subcategory.id, purchaseUnitId: buyUnit.id, saleUnitId: saleUnit.id, sku: key + '-' + index, internalCode: key + '-' + index, name: key + ' Producto ' + index } }));
      const supplier = await tx.supplier.create({ data: { companyId, code: key, name: key, countryId: 1 } });
      const slot = await tx.location.create({ data: { warehouseId: general.id, code: key, aisle: key, rack: '1', level: '1', position: '1', capacity: 100 } });
      const expenseType = await tx.expenseType.create({ data: { companyId, name: key } });
      let request = await purchases.createRequest({ branchId: general.branchId, warehouseId: general.id, purpose: 'resale', requiredDate: future, justification: key, details: products.map((product, index) => ({ productId: product.id, unitId: buyUnit.id, quantity: index + 2 })) }, actor.id, companyId);
      request = await purchases.submitRequest(request.id, actor.id, companyId);
      let process = await supply.create({ dateFrom: day, dateTo: day, requestIds: [request.id] }, companyId, actor.id);
      process = await supply.reviewQuantities(process.id,'submit',{expectedRevision:process.quantityRevision},companyId,actor.id);
      process = await supply.reviewQuantities(process.id,'approve',{expectedRevision:process.quantityRevision},companyId,actor.id);
      process = await supply.rfq(process.id, { supplierId: supplier.id, lineIds: process.lines.map(line => line.id) }, companyId, actor.id);
      const rfq = process.rfqs[0]!;
      const quotation = await purchases.createQuotation({ rfqId: rfq.id, supplierId: supplier.id, requestIds: [], quotationDate: day, validUntil: future, currency: 'USD', details: rfq.lines.map((line, index) => ({ productId: line.line.productId, unitId: buyUnit.id, quantity: Number(line.quantity), availableQuantity: Number(line.quantity), unitPrice: index ? 5 : 10, discount: index ? 0 : 1, taxRate: 13, sources: [] })) }, actor.id, companyId, user);
      await purchases.receiveQuotation(quotation.id, actor.id, companyId);
      const award = { requestId: randomUUID(), branchId: general.branchId, warehouseId: general.id, details: quotation.details.map(detail => ({ quotationDetailId: detail.id, quantity: Number(detail.quantity) })) };
      process = await supply.award(process.id, award, companyId, user);
      const order = await purchases.order(process.orders[0]!.id, companyId);
      await reject(purchases.receiveOrder(order.id, { requestId: randomUUID(), items: [{ orderDetailId: order.details[0]!.id, quantity: 1 }] }, actor.id, companyId));
      await purchases.submitOrder(order.id, actor.id, companyId);
      await purchases.approveOrder(order.id, actor.id, companyId);
      await purchases.sendOrder(order.id, actor.id, companyId);
      const cancelledPayload = { requestId: randomUUID(), supplierInvoiceNumber: key + ' CANCELADA', items: [{ orderDetailId: order.details[0]!.id, quantity: 1 }] };
      const availableSlots = await tx.location.findMany({ where: { warehouseId: general.id, isActive: true, deletedAt: null }, select: { id: true } });
      await tx.location.updateMany({ where: { id: { in: availableSlots.map(location => location.id) } }, data: { isActive: false } });
      await purchases.receiveOrder(order.id, cancelledPayload, actor.id, companyId);
      const cancelled = await tx.purchase.findUniqueOrThrow({ where: { uuid: cancelledPayload.requestId }, include: { items: true } });
      assert.equal(cancelled.items[0]!.locationId, null); assert.equal(cancelled.items[0]!.suggestedLocationId, null);
      assert.equal(await tx.inventoryStock.count({ where: { productId: { in: products.map(product => product.id) } } }), 0);
      await tx.location.updateMany({ where: { id: { in: availableSlots.map(location => location.id) } }, data: { isActive: true } });
      console.log('PASS receipt without available spaces: remains pending, no automatic stock or occupied location');
      await supply.place(cancelled.items[0]!.id, { locationId: slot.id, barcode: products[0]!.internalCode, confirmed: true }, companyId, actor.id);
      await receipts.transition(cancelled.id, 'cancel', 'QA cancelación de recepción parcial', actor.id, companyId);
      assert.equal(Number((await tx.inventoryStock.findUniqueOrThrow({ where: { productId_locationId: { productId: products[0]!.id, locationId: slot.id } } })).quantity), 0);
      assert((await purchases.order(order.id, companyId)).details.every(detail => detail.receivedQuantity.eq(0)));
      await reject(purchases.receiveOrder(order.id, cancelledPayload, actor.id, companyId));
      await reject(receipts.transition(cancelled.id, 'cancel', 'QA no repetir reversión', actor.id, companyId));
      assert.equal(await tx.inventoryMovement.count({ where: { purchaseItemId: cancelled.items[0]!.id, type: 'REVERSAL' } }), 1);
      console.log('PASS cancellation: exact stock reversal, restored order balance and blocked duplicate/cancelled retry');

      const payload = { requestId: randomUUID(), supplierInvoiceNumber: key + ' FACTURA', items: order.details.map(detail => ({ orderDetailId: detail.id, quantity: Number(detail.quantity), locationId: slot.id })) };
      await purchases.receiveOrder(order.id, payload, actor.id, companyId);
      const receipt = await tx.purchase.findUniqueOrThrow({ where: { uuid: payload.requestId }, include: { items: true } });
      assert.equal(Number(receipt.items.reduce((sum, item) => sum + Number(item.lineTotal), 0).toFixed(2)), 34);
      await reject(receipts.transition(receipt.id, 'verify', undefined, actor.id, companyId));
      for (const item of receipt.items) await supply.place(item.id, { locationId: slot.id, barcode: products.find(product => product.id === item.productId)!.internalCode, confirmed: true }, companyId, actor.id);
      await receipts.transition(receipt.id, 'verify', undefined, actor.id, companyId);
      for (const [reference, categoryName, amount, capitalizable] of [['FLETE', 'freight', .03, true], ['GASTO', 'expense', .02, true], ['DAI', 'dai', .04, true], ['IVA', 'expense', 13, false]] as const) await supply.expense(receipt.id, { expenseTypeId: expenseType.id, reference: key + '-' + reference, category: categoryName, amount, capitalizable }, companyId, actor.id);
      const costPayload = { purchaseId: receipt.id, totalFreight: 999, totalExpenses: 999, totalDai: 999, importVat: 13, details: receipt.items.map(item => ({ purchaseItemId: item.id, costFob: Number(item.lineTotal) })) };
      let cost = await retaceos.create(costPayload, actor.id, companyId);
      await reject(retaceos.close(cost.id, actor.id, companyId));
      cost = await retaceos.calculate(cost.id, actor.id, companyId);
      assert.equal(Number(cost.totalCost), 34.09);
      assert.deepEqual(cost.details.map(detail => Number(detail.totalCost)), [19.05, 15.04]);
      assert.equal(cost.expenseAllocations.length, 3);
      await retaceos.cancel(cost.id, 'QA reemplazo sin gastos duplicados', actor.id, companyId);
      assert.equal(await tx.purchaseExpenseAllocation.count({ where: { retaceoId: cost.id } }), 0);
      cost = await retaceos.create(costPayload, actor.id, companyId);
      cost = await retaceos.calculate(cost.id, actor.id, companyId);
      await retaceos.calculate(cost.id, actor.id, companyId);
      assert.equal(await tx.purchaseExpenseAllocation.count({ where: { retaceoId: cost.id } }), 3);
      await retaceos.verify(cost.id, actor.id, companyId);
      await retaceos.close(cost.id, actor.id, companyId);
      await receipts.transition(receipt.id, 'close', undefined, actor.id, companyId);
      await reject(retaceos.update(cost.id, { totalFreight: 100 }, actor.id, companyId));
      await reject(retaceos.cancel(cost.id, 'QA inmutable', actor.id, companyId));
      await reject(receipts.transition(receipt.id, 'cancel', 'QA cierre inmutable', actor.id, companyId));
      assert.equal(Number((await tx.inventoryStock.aggregate({ where: { locationId: slot.id }, _sum: { quantity: true } }))._sum.quantity), 5);
      assert.equal(await tx.inventoryMovement.count({ where: { purchaseItem: { purchaseId: receipt.id } } }), 2);
      console.log('PASS multi-product cost: $34 net FOB + $0.09 actual costs = $34.09; exact cents, DAI and VAT exclusion');
      console.log('PASS costing lifecycle: cancellation releases allocations, recalculation is idempotent and closed documents are immutable');
      verified = true;
      throw rollback;
    }, { timeout: 60000 });
  } catch (error) { if (error !== rollback) throw error; }
  assert(verified);
  assert.equal(await db.product.count({ where: { sku: { startsWith: key } } }), 0);
  assert.equal(await db.purchaseRequest.count({ where: { justification: key } }), 0);
  console.log('PASS rollback: edge-case data and audit events left no additional purchasing process');
}
main().catch(error => { console.error(error); process.exitCode = 1; }).finally(() => db.$disconnect());
