<script setup lang="ts">
import { onBeforeUnmount, ref, watch } from 'vue';
import { Search, RefreshCw, RotateCcw, Trash2, X, ChevronLeft, ChevronRight } from 'lucide-vue-next';
import AdminLayout from '../layouts/AdminLayout.vue';
import AdministrationNav from '../components/admin/AdministrationNav.vue';
import AppButton from '../components/base/AppButton.vue';
import PurchaseActionDialog from '../components/base/PurchaseActionDialog.vue';
import TrashButton from '../components/admin/TrashButton.vue';
import { http } from '../services/http.service';
import { activeCompanyId } from '../services/company-context';
import { usePermissions } from '../composables/usePermissions';
import { getApiErrorMessage } from '../utils/api-error';
const {can}=usePermissions();const entities=ref<{key:string;label:string}[]>([]),rows=ref<any[]>([]),records=ref<any[]>([]);
const search=ref(''),entity=ref(''),page=ref(1),pages=ref(0),total=ref(0),loading=ref(false),busy=ref(false),error=ref(''),success=ref('');
const browser=ref(false),recordEntity=ref('products'),recordSearch=ref(''),recordPage=ref(1),recordPages=ref(0),recordLoading=ref(false),restoreItem=ref<any>(null);
const purgeSelection=ref<{ids:number[];label:string;companyId:number}|null>(null),previewing=ref(false);
let companyEpoch=0;
async function preparePurge(row?:any){
 if(busy.value||previewing.value||!can('trash.purge')||!activeCompanyId.value)return;
 const companyId=activeCompanyId.value,epoch=companyEpoch;error.value='';
 if(row){purgeSelection.value={ids:[row.id],label:row.label,companyId};return;}
 previewing.value=true;
 try{const r=await http.get('/trash/purge-preview',config());if(epoch!==companyEpoch)return;purgeSelection.value=r.data.data.count?{ids:r.data.data.ids,label:`Los ${r.data.data.count} registros de la papelera de esta empresa`,companyId}:null;if(!r.data.data.count)success.value='La papelera está vacía.';}
 catch(e){if(epoch===companyEpoch)error.value=getApiErrorMessage(e,'No se pudo preparar la eliminación');}
 finally{if(epoch===companyEpoch)previewing.value=false;}
}
async function purge(){
 const selection=purgeSelection.value;if(busy.value||!selection||selection.companyId!==activeCompanyId.value||!can('trash.purge'))return;
 const epoch=companyEpoch;busy.value=true;error.value='';
 try{const r=await http.post('/trash/purge',{ids:selection.ids,confirmed:true},{headers:{'X-Company-Id':String(selection.companyId)}});if(epoch!==companyEpoch)return;purgeSelection.value=null;success.value=r.data.data.retained?'Registros eliminados de forma definitiva. Se conservaron las referencias históricas necesarias; ya no pueden recuperarse.':'Registros eliminados definitivamente.';await load();if(epoch===companyEpoch&&page.value>Math.max(1,pages.value))page.value=Math.max(1,pages.value);}
 catch(e){if(epoch===companyEpoch)error.value=getApiErrorMessage(e,'No se pudo eliminar definitivamente');}
 finally{if(epoch===companyEpoch)busy.value=false;}
}
watch(activeCompanyId,()=>{companyEpoch++;purgeSelection.value=null;previewing.value=false;busy.value=false;},{flush:'sync'});
let version=0,recordVersion=0,timer:ReturnType<typeof setTimeout>|undefined;
onBeforeUnmount(()=>{version++;recordVersion++;clearTimeout(timer);});
const config=()=>({headers:{'X-Company-Id':String(activeCompanyId.value)}});
const date=(d:string)=>new Intl.DateTimeFormat('es-SV',{dateStyle:'medium',timeStyle:'short',timeZone:'America/El_Salvador'}).format(new Date(d));
async function load(){if(!activeCompanyId.value)return;const token=++version;loading.value=true;error.value='';try{const r=await http.get('/trash',{...config(),params:{search:search.value,entity:entity.value,page:page.value}});if(token!==version)return;rows.value=r.data.data.items;total.value=r.data.data.total;pages.value=r.data.data.pages;}catch(e){if(token===version)error.value=getApiErrorMessage(e,'No se pudo cargar la papelera');}finally{if(token===version)loading.value=false;}}
async function loadRecords(){if(!browser.value||!recordEntity.value)return;const token=++recordVersion;recordLoading.value=true;error.value='';try{const r=await http.get('/trash/records/'+recordEntity.value,{...config(),params:{search:recordSearch.value,page:recordPage.value}});if(token!==recordVersion)return;records.value=r.data.data.items;recordPages.value=r.data.data.pages;}catch(e){if(token===recordVersion)error.value=getApiErrorMessage(e,'No se pudieron cargar los registros');}finally{if(token===recordVersion)recordLoading.value=false;}}
async function restore(){if(busy.value||!restoreItem.value)return;busy.value=true;error.value='';const company=activeCompanyId.value,epoch=companyEpoch;try{await http.post('/trash/'+restoreItem.value.id+'/restore',{},config());if(epoch!==companyEpoch||company!==activeCompanyId.value)return;restoreItem.value=null;success.value='Registro restaurado en su módulo de origen.';await load();}catch(e){if(epoch===companyEpoch)error.value=getApiErrorMessage(e,'No se pudo restaurar');}finally{if(epoch===companyEpoch)busy.value=false;}}
watch(activeCompanyId,async()=>{version++;recordVersion++;rows.value=[];records.value=[];browser.value=false;restoreItem.value=null;page.value=1;success.value='';if(!activeCompanyId.value)return;const company=activeCompanyId.value;try{const r=await http.get('/trash/entities',config());if(company!==activeCompanyId.value)return;entities.value=r.data.data;recordEntity.value=entities.value.some(e=>e.key==='products')?'products':entities.value[0]?.key||'';await load();}catch(e){if(company===activeCompanyId.value)error.value=getApiErrorMessage(e,'No se pudo cargar la configuración');}},{immediate:true});
watch([search,entity],()=>{page.value=1;clearTimeout(timer);timer=setTimeout(()=>void load(),250);});
watch(page,()=>void load());watch([recordEntity,recordSearch],()=>{recordPage.value=1;void loadRecords();});watch([browser,recordPage],()=>void loadRecords());
function deleted(){success.value='Registro enviado a papelera. Disponible durante 30 días.';void loadRecords();void load();}
</script>
<template><AdminLayout title="Configuración · Papelera"><div class="mx-auto max-w-5xl space-y-5">
<AdministrationNav section="trash" />
<header class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="page-title">Papelera</h1><p class="page-subtitle">Recupera los registros eliminados durante los siguientes 30 días.</p></div><div class="flex flex-wrap gap-2"><AppButton v-if="can('trash.purge')" variant="outline" :disabled="loading || busy || previewing || (!total && !search && !entity)" @click="preparePurge()"><Trash2 class="h-4 w-4"/>Vaciar papelera</AppButton><AppButton variant="outline" :disabled="loading || busy" @click="load"><RefreshCw class="h-4 w-4"/>Actualizar</AppButton><AppButton v-if="can('trash.delete')" variant="outline" @click="browser=true"><Trash2 class="h-4 w-4"/>Eliminar registros</AppButton></div></header>
<p v-if="error" role="alert" class="rounded-lg bg-danger/10 p-3 text-sm text-danger">{{error}}</p><p v-if="success" role="status" class="text-sm text-success">{{success}}</p>
<div class="flex flex-wrap gap-3"><label class="relative min-w-60 flex-1"><Search class="absolute left-3 top-3 h-4 w-4 text-muted-fg"/><input v-model="search" aria-label="Buscar eliminados" placeholder="Buscar registro eliminado" class="field-control !mt-0 !pl-9"/></label><select v-model="entity" aria-label="Filtrar por módulo" class="field-control !mt-0 max-w-xs"><option value="">Todos los módulos</option><option v-for="e in entities" :key="e.key" :value="e.key">{{e.label}}</option></select></div>
<div class="surface-panel"><p v-if="loading" class="p-8 text-center text-muted-fg">Cargando…</p><p v-else-if="!rows.length" class="p-12 text-center text-muted-fg">{{search || entity ? 'No hay coincidencias.' : 'La papelera está vacía.'}}</p><div v-else class="divide-y divide-border"><article v-for="row in rows" :key="row.id" class="flex flex-wrap items-center justify-between gap-4 p-5"><div class="min-w-0"><p class="font-medium break-words">{{row.label}}</p><p class="mt-1 text-xs text-muted-fg">{{row.module}} · Eliminado el {{date(row.deletedAt)}}</p><p class="mt-2 text-xs text-muted-fg">Disponible para recuperar hasta {{date(row.expiresAt)}} · {{row.daysLeft}} días restantes</p></div><div class="flex flex-wrap gap-2"><AppButton v-if="can('trash.restore')" variant="outline" :disabled="busy || previewing" @click="restoreItem=row;error=''"><RotateCcw class="h-4 w-4"/>Restaurar</AppButton><AppButton v-if="can('trash.purge')" variant="outline" :disabled="busy || previewing" @click="preparePurge(row)"><Trash2 class="h-4 w-4"/>Eliminar definitivamente</AppButton></div></article></div></div>
<div v-if="total" class="flex items-center justify-between text-sm text-muted-fg"><span>{{total}} registros</span><div class="flex items-center gap-3"><button class="icon-button" aria-label="Página anterior" :disabled="loading || page<=1" @click="page--"><ChevronLeft class="h-4 w-4"/></button>{{page}} / {{pages}}<button class="icon-button" aria-label="Página siguiente" :disabled="loading || page>=pages" @click="page++"><ChevronRight class="h-4 w-4"/></button></div></div>
</div>
<div v-if="browser" class="fixed inset-0 z-40 flex justify-end bg-black/40" @click.self="browser=false;recordVersion++"><aside role="dialog" aria-modal="true" aria-label="Enviar registros a papelera" class="h-full w-full max-w-2xl overflow-y-auto bg-surface p-6 shadow-xl" @keydown.esc="browser=false;recordVersion++"><header class="flex items-center justify-between"><h2 class="text-xl font-semibold">Eliminar registros</h2><button class="icon-button" aria-label="Cerrar" @click="browser=false;recordVersion++"><X class="h-4 w-4"/></button></header><div class="my-5 space-y-3"><label class="text-sm">Módulo<select v-model="recordEntity" class="field-control"><option v-for="e in entities" :key="e.key" :value="e.key">{{e.label}}</option></select></label><input v-model="recordSearch" type="search" aria-label="Buscar registros del módulo" placeholder="Buscar nombre, código o ID" class="field-control"/></div><p v-if="error" role="alert" class="text-danger text-sm">{{error}}</p><p v-if="recordLoading" class="py-6 text-muted-fg">Cargando…</p><div v-else class="divide-y divide-border"><div v-for="r in records" :key="r.id" class="flex flex-wrap items-center justify-between gap-3 py-4"><div class="min-w-0"><p class="font-medium break-words">{{r.label}}</p><p class="mt-1 text-xs text-muted-fg">#{{r.id}}</p></div><TrashButton :entity="recordEntity" :record-id="r.id" :label="r.label" @deleted="deleted"/></div><p v-if="!records.length" class="py-8 text-center text-muted-fg">No hay registros disponibles.</p></div><div v-if="recordPages>1" class="mt-4 flex justify-end gap-3"><button class="icon-button" :disabled="recordPage<=1||recordLoading" aria-label="Registros anteriores" @click="recordPage--"><ChevronLeft class="h-4 w-4"/></button><span class="self-center text-xs">{{recordPage}} / {{recordPages}}</span><button class="icon-button" :disabled="recordPage>=recordPages||recordLoading" aria-label="Registros siguientes" @click="recordPage++"><ChevronRight class="h-4 w-4"/></button></div></aside></div>
<PurchaseActionDialog v-if="restoreItem" title="Restaurar registro" :description="restoreItem.label + ': volverá a su módulo con sus relaciones originales.'" :busy="busy" :error="error" @close="restoreItem=null" @confirm="restore"/>
<PurchaseActionDialog v-if="purgeSelection" :title="purgeSelection.ids.length === 1 ? 'Eliminar definitivamente' : 'Vaciar papelera'" :description="purgeSelection.label + ': esta acción no se puede deshacer. Los registros con movimientos o relaciones históricas conservarán esas referencias, pero no podrán recuperarse.'" confirm-label="Eliminar definitivamente" destructive :busy="busy" :error="error" @close="!busy && (purgeSelection=null)" @confirm="purge"/>
</AdminLayout></template>
